### ISSUE TITLE
can you add walk / iterate / get all, and so on?

### ISSUE THREAD

**Issue by gokch** [Yiling-J/theine-go#13]
I want to find all values ​​without input key.
It would be nice if there was also a query function.
If the work is difficult, I will contribute.

**Comment by Yiling-J** [comment]
It's not difficult but if you are interested to this, you can open a PR. Or I will do it this week. Basic idea is just hold a rlock and loop each shard. I think there will be an iterator struct, and this struct should have a next method.

**Comment by Yiling-J** [comment]
I think `Iter(func(key Key, value Value))` is better, it's hard to relase lock if there is an explicit Next method

**Comment by RJKeevil** [comment]
Seconded, I wish to use this to dump all values to disk in order to perform a warm restart.

Fantastic work by the way, excellent library!

**Comment by Yiling-J** [comment]
@RJKeevil Glad to hear that! Let's wait @gokch first if he is willing to help. If he has no time I will add this feature tomorrow.

**Comment by gokch** [comment]
I didn't understand this code now, but it would be nice to add some code like this.
( I don't know whether to lock all at once or lock per shard )

```
func (s *Store[K, V]) Iter(fn func(key K, value V) bool) bool {
	for _, shard := range s.shards {
		shard.mu.RLock()
		for _, entry := range shard.hashmap {
			if ok := fn(entry.key, entry.value); !ok {
				shard.mu.RUnlock()
				return false
			}
		}
		shard.mu.RUnlock()
	}
	return true
}
```

add filter ( prefix, order, limit, offset, ttl, key only ) also would be a good feature.
anyway, it`s nice code. sorry for not being of help.

**Comment by Yiling-J** [comment]
@RJKeevil @gokch Because timingwheel is not realtime, there might be expired entries in cache. I will exclude expired entries in `Range`(call it Range to keep consistency with sync.map), is that OK? Or I can include expire and cost in range function

**Comment by RJKeevil** [comment]
For my use case expired entries are fine, my purpose is to restart my process with broadly the same cache available (via store to json and load from json).  This will reset any expiry timers in the new cache anyway, which will then sort themselves out over time based on usage.

**Comment by Yiling-J** [comment]
@RJKeevil If excluding expired entries is not a problem to you , I think I will do that. It's just serveral lines of code. The only reason expired entries may exist is because timingwheel is not a perfect proactive ttl expiration solution.

**Comment by Yiling-J** [comment]
@gokch new API is `Range(f func(key K, value V) bool)`, if this is ok I'll merge and release

**Comment by RJKeevil** [comment]
Quick sense check, I tested out your branch, range works nicely but I see duplicate keys coming out of the range function.  The cache values do get updated in my test, perhaps all versions are being returned, not the latest?

**Comment by Yiling-J** [comment]
@RJKeevil can you please pull latest code and test again? I think it has been fixed.

**Comment by RJKeevil** [comment]
Yep all sorted, thanks
