### ISSUE TITLE
Don't use automaxprocs

### ISSUE THREAD

**Issue by rrb3942** [Yiling-J/theine-go#16]
I like the automaxprocs library, but I don't think it is correct to use inside of another library that gets imported.

Decisions on how to handle GOMAXPROCS should be left up to the main application, as it can have unintended performance implications depending on the workload.

If you find that cache benchmarks run better with it, consider maybe just using inside of benchmarks.

Was a bit surprised when something started messing with my GOMAXPROCS when I was converting a project over to this library!

**Comment by Yiling-J** [comment]
Thanks and good point! Let me remove that

**Comment by Yiling-J** [comment]
@rrb3942 released, please try v0.2.5
