### ISSUE TITLE
For HybridCache, cache size setting for DRAM vs NVM

### ISSUE THREAD

**Issue by salarali** [Yiling-J/theine-go#38]
Sorry, if I am missing something obvious, but is there a way to set a max value for DRAM, when using HybridCache?

I want the cache to only store 1GB of data in memory (DRAM) and rest in NVM. Is that something that can be configured?

**Comment by Yiling-J** [comment]
Using HybridCache is a two-step process:
```go
nvm, err := theine.NewNvmBuilder[int, int]("cache", 150<<20).[settings...].Build()

client, err := theine.NewBuilder[int, int](100).Hybrid(nvm).Build()
```
As you can see, both builders require a size parameter.

BTW considering HybridCache isn't widely used(you are the first one AFAIK), make sure do some tests before deploying it.

**Comment by salarali** [comment]
Ah it was something obvious. Thanks for the quick reply. 

Will let u know if I encounter any issues.
