### ISSUE TITLE
Remove ristretto dependency

### ISSUE THREAD

**Issue by salarali** [Yiling-J/theine-go#5]
Would it be possible to move the benchmark_test.go into another folder so that `theine-go` isnt dependant on `ristretto`?

**Comment by Yiling-J** [comment]
Thank you for your suggestion, but I think go get won't install test dependencies? So if you use Theine as a package, that's not a problem. To remove it from go mod, I think I have to create a sub module

**Comment by Yiling-J** [comment]
I think you are right, I will remove that file because all benchmarks are moved to [go-cache-benchmark-plus](https://github.com/Yiling-J/go-cache-benchmark-plus) repo

**Comment by salarali** [comment]
It does add the dependencies because they are listed in go.mod.

**Comment by Yiling-J** [comment]
is that true? I just create a test project and run `go get github.com/Yiling-J/theine-go`, this is the go mod file:
```
module box

go 1.20

require github.com/Yiling-J/theine-go v0.2.0

require (
	github.com/gammazero/deque v0.2.1 // indirect
	github.com/klauspost/cpuid/v2 v2.0.9 // indirect
	github.com/zeebo/xxh3 v1.0.2 // indirect
)


```

**Comment by Yiling-J** [comment]
removed in https://github.com/Yiling-J/theine-go/pull/6

**Comment by salarali** [comment]
Hmm.. I was mistaken. Apologies.
